basePath: /
definitions:
  main.CaptureRequest:
    properties:
      code:
        example: QZNWZI
        type: string
      ip:
        example: 192.168.68.126
        type: string
    type: object
  main.Snapshot:
    properties:
      captured_at:
        type: string
      filename:
        type: string
      id:
        type: integer
    type: object
host: localhost:3000
info:
  contact: {}
  description: Capture snapshot from EZVIZ camera over RTSP.
  title: EZVIZ RTSP Snapshot API
  version: "1.0"
paths:
  /capture-multiple:
    post:
      consumes:
      - application/json
      parameters:
      - description: Camera IP and RTSP code
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.CaptureRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Snapshot'
            type: array
      summary: Capture multiple snapshots
swagger: "2.0"
